config/routes.rb
Rails.application.routes.draw do

  get 'reservations/confirm'
  get 'reservations/show'
  get 'reservations/index'
  root 'static_pages#home'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users, only: [:create, :update, :destroy] do
    member do
      get 'account', 'profile', 'reserving'
      patch 'account_update'
    end
  end  

  resources :rooms do
    member do
      get 'registered'
    end
  end

  resources :reservations, only: [:create, :destroy] do
    collection do
      post :confirm
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  has_many :reservations
  has_many :reserving, through: :reservations, source: :room
  has_many :rooms, dependent: :destroy
  has_one_attached :image
  before_save { email.downcase! }
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum:255}, format: {with: VALID_EMAIL_REGEX}, 
                  uniqueness: true
  validates :password, presence: true, length: {minimum: 6}, allow_nil: true
  validates :description, length: {maximum: 300}
  validates :image, content_type: {in: %w[image/jpeg image/gif image/png],
                            message: "はjpeg, gif, pngのいずれかのフォーマットを選択できます。"},
              size: {less_than: 5.megabytes, message: "のファイルサイズは5MB以下にしてください。"}

  has_secure_password

  class << self
  # 渡された文字列のハッシュ値を返す
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def feed
    Room.where("user_id = ?", id)
  end

  def display_image
    image.variant(resize_to_limit: [500, 500])
  end

  def cancel(room)
    Reservations.find_by(room_id: room.id).destroy
  end

  def reserving?(room)
    reserving.include?(room)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:account, :profile, :update, :account_update, :reserving]
  before_action :correct_user, only: [:account, :profile, :update, :account_update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.image.attach(params[:user][:image])
    if @user.save
      log_in @user
      flash[:success] = "#{@user.name}さん、Potepan Shareへようこそ!"
      redirect_to profile_user_url(@user)
    else
      render 'new'
    end
  end

  def account
    @user = User.find(params[:id])
  end

  def profile
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "プロフィールを更新しました"
      redirect_to profile_user_path(@user)
    else
      render 'profile'
    end
  end

  def account_update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "アカウントを更新しました"
      redirect_to account_user_path(@user)
    else
      render 'account'
    end
  end

  def reserving
    @user = User.find(params[:id])
    @reservations = Reservation.find_by(room_id: @user.reserving.ids)
    @reserving_rooms = @user.reserving.paginate(page: params[:page], per_page: 32)
  end


  def destroy
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :description, :image)
    end


    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.slim
.device-form
  = render 'shared/error_messages', object: @user
  = form_with(model: @user, local: true) do |f|
    .form-row
      .required
        span.white 必須
      = f.text_field :name, placeholder: "名前"
    .form-row
      .required
        span.white 必須
      = f.email_field :email, placeholder: "メールアドレス"
    .form-row
      .required
        span.white 必須
      = f.password_field :password, placeholder: "パスワード"
    .form-row
      .required
        span.white 必須
      = f.password_field :password_confirmation, placeholder: "パスワード確認"
    .form-btn
      = f.submit "新しいアカウントを作成", class: "btn btn-primary white"
      = link_to "すでにアカウントをお持ちの方はログイン", login_path

app/views/users/_user_nav.html.slim
.user-nav
  ul
    li#account
      = link_to "アカウント", account_user_path(@user)
    li#profile
      = link_to "プロフィール", profile_user_path(@user)

app/views/users/account.html.slim
.row
  .user-nav
    ul
      li.active
        = link_to "アカウント", account_user_path(@user)
      li
        = link_to "プロフィール", profile_user_path(@user)
  .user-view
    .device-frame
      .device-form
        p アカウント
        = render 'shared/error_messages', object: @user
        = form_with(model: @user, local: true, url: account_update_user_url) do |f|          
          .form-row
            = f.label :email
            = f.email_field :email, placeholder: "メールアドレス"
          .form-row
            = f.label :password
            = f.password_field :password, placeholder: "パスワード"
          .form-row
            = f.label :password_confirmation
            = f.password_field :password_confirmation, placeholder: "パスワード確認"
          .form-btn
            = f.submit "編集", class: "btn btn-primary white"

app/views/users/new.html.slim
.container
  .device-frame
    p 新しいアカウントを作成
    =render 'form'
      

app/views/users/profile.html.slim
.row
  .user-nav
    ul
      li
        = link_to "アカウント", account_user_path(@user)
      li.active
        = link_to "プロフィール", profile_user_path(@user)
  .user-view
    .device-frame
      .device-form
        p プロフィール
        = render 'shared/error_messages', object: @user
        = form_with(model: @user, local: true) do |f|          
          .form-row
            = f.label :name
            = f.text_field :name, placeholder: "名前"
          .form-row
            = f.label :description
            = f.text_area :description, placeholder: "自己紹介を記入できます。"
          .form-row
            =f.label :image
            = f.file_field :image, accept: "image/jpeg,image/gif,image/png"
          .form-btn
            = f.submit "編集", class: "btn btn-primary white"

app/views/users/reserving.html.slim
.room-container
  .room-items
    -if @reserving_rooms.any?
      h3 登録ルーム数: #{@reserving_rooms.count}件
      span #{@reserving_rooms.offset_value} 〜 #{@reserving_rooms.offset_value + @reserving_rooms.length}件表示しています。
      table.reserving-table
        thead
          tr
            th ルーム画像
            th ルーム名
            th 合計料金
            th 開始日
            th 終了日
            th 予約確定日時
        tbody
          - @reserving_rooms.each do |room|
            tr
              td.room-img
               = link_to room_path(room)
                .image-frame
                  -if room.image.attached?
                    = image_tag room.display_image, class: "room-icon"
                  - else
                    = image_tag "room01.jpg", class: "room-icon"
              td.room-name 
                = link_to "#{room.name}", room_path(room)
              td.total-fee ¥#{room.get_reservations_info(@user).total_fee}
              td.start-date #{room.get_reservations_info(@user).start_date.to_s(:date_jp)}
              td.end-date #{room.get_reservations_info(@user).end_date.to_s(:date_jp)}
              td.created-at #{room.get_reservations_info(@user).created_at.to_s(:datetime_jp)}
              td.cancel-btn
                = link_to 'キャンセル', room.get_reservations_info(@user), method: :delete, data: {confirm: "ルームを削除しますか？"}, class: 'white btn btn-delete'
      = paginate @reserving_rooms 
    - else
      .not-found
        h1 現在ご予約しているお部屋はございません。