config/routes.rb
Rails.application.routes.draw do

  get 'reservations/confirm'
  get 'reservations/show'
  get 'reservations/index'
  root 'static_pages#home'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users, only: [:create, :update, :destroy] do
    member do
      get 'account', 'profile', 'reserving'
      patch 'account_update'
    end
  end  

  resources :rooms do
    member do
      get 'registered'
    end
  end

  resources :reservations, only: [:create, :destroy] do
    collection do
      post :confirm
    end
  end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :reservations, dependent: :destroy
  has_one_attached :image
  default_scope -> {order(created_at: :desc)}
  validates :user_id, presence: true
  validates :name, presence: true, length: {maximum: 50}
  validates :description, presence: true, length: {maximum: 200}
  validates :fee, numericality: {only_integer: true}
  validates :address, presence: true
  validates :image, content_type: {in: %w[image/jpeg image/gif image/png],
                message: "jpeg, gif, pngのいずれかのフォーマットを選択してください"},
              size: {less_than: 5.megabytes, message: "ファイルサイズは5MB以下にしてください。"}

  def display_image
    image.variant(resize_to_limit: [500, 500])
  end

  def get_reservations_info(user)
    Reservation.where('user_id = ? and room_id = ?',user.id, id).first
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :logged_in_user
  before_action :correct_user, only: [:edit, :update, :destroy]
  def index
    @rooms = @q.result(distinct: true).paginate(page: params[:page], per_page: 32)
  end

  def show
    @room = Room.find(params[:id])
    @reservation = current_user.reservations.build
  end

  def registered
    @rooms = current_user.feed.paginate(page: params[:page], per_page: 32)
  end

  def new
    @room = current_user.rooms.build
  end

  def create
    @room = current_user.rooms.build(room_params)
    @room.image.attach(params[:room][:image])
    if @room.save
      flash[:success] = "ルームを登録しました"
      redirect_to root_path
    else
      @rooms = current_user.feed.paginate(page: params[:page], per_page: 32)
      render 'new'
    end
  end

  def update
    if @room.update(room_params)
      flash[:success] = "ルームを更新しました"
      redirect_to room_path(@room)
    else
      render 'profile'
    end
  end

  def destroy
    @room.destroy
    flash[:success] = "ルームを削除しました"
    redirect_to root_path
  end

  private
    def room_params
      params.require(:room).permit(:name,:description,:image,:fee,:address)
    end

    def correct_user
      @room = current_user.rooms.find_by(id: params[:id])
      redirect_to root_url if @room.nil?
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.slim
.device-form
  = render 'shared/error_messages', object: @room
  = form_with(model: @room, local: true) do |f|
    .form-row
      .required
        span.white 必須
      = f.text_field :name, placeholder: "名前"
    .form-row
      = f.label :image
      = f.file_field :image, accept: "image/jpeg,image/gif,image/png"
    .form-row
      .required
        span.white 必須
      = f.text_area :description, placeholder: "説明"
    .form-row
      .required
        span.white 必須
      span.yen ¥
      = f.text_field :fee, placeholder: "料金 / 1拍"
    .form-row
      .required
        span.white 必須
      = f.text_field :address, placeholder: "住所"
    .form-btn
      = f.submit "ルームを登録", class: "btn btn-primary white"

app/views/rooms/_room.html.slim
li
  = link_to room_path(room)
    .image-frame
      -if room.image.attached?
        = image_tag room.display_image, class: "room-icon"
      - else
        = image_tag "room01.jpg", class: "room-icon"
    .content
      span.name #{room.name}
      span.address #{room.address}
      span.fee ¥#{room.fee}

app/views/rooms/edit.html.slim
.container
  .device-frame
    p ルームを更新
    =render 'form'
      

app/views/rooms/index.html.slim
.room-container
  .room-items
    h3 検索結果: #{@rooms.count}件
    -if @rooms.any?
      span #{@rooms.offset_value} 〜 #{@rooms.offset_value + @rooms.length}件表示しています。
      ol
        = render @rooms
      = paginate @rooms
    -else
      .not-found
        h1 検索結果にマッチしたお部屋が見つかりませんでした

app/views/rooms/new.html.slim
.container
  .device-frame
    p 新しいルームを登録
    =render 'form'

app/views/rooms/registered.html.slim
.room-container
  .room-items
    -if @rooms.any?
      h3 登録ルーム数: #{@rooms.count}件
      span #{@rooms.offset_value} 〜 #{@rooms.offset_value + @rooms.length}件表示しています。
      ol
        = render @rooms
      = paginate @rooms
    - else
      .not-found
        h1 現在ご登録しているお部屋はございません。

app/views/rooms/show.html.slim
.container.show-container
  .container-left
    -if @room.image.attached?
      = image_tag @room.image, class: "room-icon", width: '500px', height: '200px'
    - else
      = image_tag "room01.jpg", class: "room-icon", width: '500px', height: '200px'
    .room-detail
      .room-owner-img
        - if @room.user.image.attached?
          = image_tag @room.user.display_image, class: "user-icon"
        - else
          = image_tag "room01.jpg", class: "user-icon"
      .room-profile
        span.name #{@room.name}
        span.address #{@room.address}
    .room-content
      p
        = @room.description
      - if current_user?(@room.user)
        .owner-container
          = link_to "編集", edit_room_path(@room), class: 'white btn btn-edit'
          = link_to "削除", @room, method: :delete, data: {confirm: "ルームを削除しますか？"}, class: 'white btn btn-delete'
  .container-right
    .reservation-nav
      .device-frame
        .fee-per-day
          i.fas.fa-yen-sign
          h3
            = "#{@room.fee} / 日"
        .device-form
          = render 'shared/error_messages', object: @reservation
          = form_with(model: @reservation, method: :post , local: true, url: confirm_reservations_path) do |f|          
            = f.hidden_field :room_id, value: @room.id
            .form-row
              = f.label :start_date
              = f.date_field :start_date
            .form-row
              = f.label :end_date
              = f.date_field :end_date
            .form-row
              = f.label :number_of_people
              = f.text_field :number_of_people
            =f.submit "確認画面へ", class: "btn btn-primary"