config/routes.rb
Rails.application.routes.draw do

  get 'reservations/confirm'
  get 'reservations/show'
  get 'reservations/index'
  root 'static_pages#home'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users, only: [:create, :update, :destroy] do
    member do
      get 'account', 'profile', 'reserving'
      patch 'account_update'
    end
  end  

  resources :rooms do
    member do
      get 'registered'
    end
  end

  resources :reservations, only: [:create, :destroy] do
    collection do
      post :confirm
    end
  end
end

app/views/layouts/_footer.html.slim
p.white © 2020 POTEPAN.INC

app/views/layouts/_header.html.slim
.header-left-nav
  = link_to root_path do
    = image_tag 'logo.png'
  = search_form_for @q, enforce_utf8: false, url: rooms_path do |f|
    .search
      i class="fas fa-map-marker-alt"
      = f.search_field :address_cont, placeholder: "エリア"
    .search
      i class="fas fa-search"
      = f.search_field :description_or_name_or_address_cont , placeholder: "キーワード"
    = f.submit "", class: 'display-none'
.header-right-nav
  - if logged_in?
    .right-nav-item.nav-user-name.white
      = current_user.name
    .right-nav-item.nav-menu.pointer.white
      - if current_user.image.attached?
        = image_tag current_user.display_image, class: "user-icon", id: "user-icon"
      - else
        = image_tag "default_icon.jpg", class: "user-icon", id: "user-icon"
      ul.dropdown.hidden-menu#dropdown
        li 
          = link_to "ルーム登録",  new_room_path
        li 
          = link_to "予約済みルーム", reserving_user_path(current_user)
        li 
          = link_to "登録済みルーム", registered_room_path(current_user)
        li 
          = link_to "設定", profile_user_path(current_user)
        li 
          = link_to "ログアウト", logout_path, method: :delete
  - else
    = link_to 'ログイン', login_path, class: 'btn btn-primary white'
    = link_to '登録する', signup_path, class: 'btn btn-secondary white'

app/views/layouts/_rails_default.html.slim
meta[name="viewport" content="width=device-width,initial-scale=1"]
script src="https://kit.fontawesome.com/7215d156bc.js" crossorigin="anonymous"
= csrf_meta_tags
= csp_meta_tag
= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | RoomReservationApp
    = render 'layouts/rails_default'
  body
    header.header
      = render 'layouts/header'
    main.main
      - flash.each do |message_type, message|        
        = content_tag(:div, message, class: "white alert alert-#{message_type}")
      = yield
    footer.footer
      = render 'layouts/footer'